
.ONESHELL:

data: 
	cd data
	g++ data_generator.cpp -o data

solution:
	g++ -Wall -O3 -std=c++17 solution.cpp -o solution 


solutionperf:
	g++ -Wall -O3 -std=c++17 solution_perf.cpp -o solutionperf

clean:
	rm solution
